#?? ??? .properties ???? ?? ??
#.? ?? ?? ??? ?? => ???: ??? ??? ???? ??.
#server.port=8081
#server.engine = "abc"
#server.framework = "bcd"

#?? ??? .yml ?? .yaml ???? ?? ??
#???? ??? ??? ?? ??? ??
#server:
#    port:8081
#    engine = "abc"